### ISSUE TITLE
we should add some `keyword` such as `//+ignore` to let the user can't see the parameter and only be used by system.

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/kubevela#1754]
we should add some `keyword` such as `//+ignore` to let the user can't see the parameter and only be used by system.

_Originally posted by @wonderflow in https://github.com/oam-dev/kubevela/pull/1748#r644563466_

**Comment by chivalryq** [comment]
The parameters are truely increasing, though I think all paramaters should be offered to end-user(otherwise it shouldn't become a param). Internal component definitions should be use, but not for all. 
Someone need more params. Also they don't want create their own component def. I think that's the problem.
