### ISSUE TITLE
Error log about generate OpenAPI v3 JSON schema when run KubeVela

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#1939]
**Describe the bug**

There are lots of error log when start KubeVela controller about generate OpenAPI v3 JSON schema

**To Reproduce**
1. install kubevela using helm
2. `kubectl logs` the pod, get log:
```
Could not capability in ConfigMap" err="failed to generate OpenAPI v3 JSON schema for capability webservice: expected '{', found 'IDENT' close (and 5 more errors)
```

**Expected behavior**

no error log

**Screenshots**

![image](https://user-images.githubusercontent.com/47812250/126297657-9c439209-938a-4d82-bb38-79ebe80367df.png)

**KubeVela Version**

source code on master branch

**Cluster information**

kin: v0.10.0 go1.15.7 darwin/amd64
k8s:Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-21T01:11:42Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Additional context**

**Comment by Somefive** [comment]
This problem is caused by a format function from cue library. The library function recognizes *if clause* as *struct* and generate invalid CUE string during formatting cue.Value to string. Therefore, when converting the string back to cue.Instance, errors are thrown.
The reason we need do this transformation is because we want to extract `parameter` field from definition. The current solution is to use LookupDef to extract the `parameter` field as cue.Value from cue.Instance. Then converting cue.Value to string and back to cue.Instance. We might be able to find solutions to work around this procedure as fixing official library bug might be too heavy.
