### ISSUE TITLE
[Feature] Configurable annotations for addon configmaps in vela-core Helm chart

### ISSUE THREAD

**Issue by kaiju** [oam-dev/kubevela#2559]
**Is your feature request related to a problem? Please describe.**

While applying the Kubevela `vela-core` helm chart via our typical configuration deployment process via ArgoCD we've run into a problem (https://github.com/argoproj/argo-cd/issues/820) applying the `fluxcd` addon ConfigMap in particular. Due to the size of the ConfigMap itself we're unable to cleanly apply the manifest via ArgoCD.

![image](https://user-images.githubusercontent.com/612224/138959308-13aac98b-4106-4db7-a7fe-59d8c7999298.png)

**Describe the solution you'd like**

ArgoCD has annotations that can be used to manage how it applies certain manifests and resources. We'd like to be able to add annotations on the addon ConfigMaps to in order to leverage ArgoCD's functionality in our Kubevela deployment and cleanly deploy the `vela-core` helm chart via ArgoCD.

Using `charts/vela-core/templates/addons/fluxcd.yaml` as an example, I figure this could be implemented as follows:
```
metadata:
  annotations:
    addons.oam.dev/description: Flux is a set of continuous and progressive delivery
      solutions for Kubernetes
    addons.oam.dev/name: fluxcd
    {{- with .Values.addons.fluxcd.configMapAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    addons.oam.dev/type: fluxcd
  name: fluxcd
  namespace: {{.Values.systemDefinitionNamespace}}
```

which would then allow us to pass additional annotations via the `addons.fluxcd.configMapAnnotations` value in Helm.

I'm happy to take a stab at implementing this myself once I unwrap how all the helm charts get generated.

**Comment by wangyikewxgm** [comment]
This issue is related the way of generate addons of version 1.1 . Before we render out the application and put then into a configmap. When install helm chart will apply these configmap to cluster. But we haver change the way of generate addon application, these cm have been removed from helm chart by https://github.com/oam-dev/kubevela/pull/2951. Please use KubeVela 1.2  directly. Let me close this pr, feel free to re-open this issue if the problem still exist.
