### ISSUE TITLE
Vela CLI not support to read default kubeconfig

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/kubevela#2728]
**What's the problem**
The default kubeconfig is ~/.kube/config. This default setting should works for all command tools related with K8s, like helm/kubectl. But vela CLI don't support that.

**Solution I want**
When `KUBECONFIG` not set, vela cli should read default config file.

**Comment by wonderflow** [comment]
@mayankkumar2 You can have a try, thanks

**Comment by mayankkumar2** [comment]
@wonderflow I think this issue doesn't exist since https://github.com/oam-dev/kubevela/blob/master/references/cli/install.go uses https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.9.5/pkg/client/config#GetConfig which automatically gets the config from .kube/config if KUBECONFIG variable is not set.

**Comment by wonderflow** [comment]
@mayankkumar2 Thanks for investigation, let's closing this issue!
