### ISSUE TITLE
Use buildkit to build docker images

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/kubevela#416]
Currently the code calls local `docker` command. We should consider using buildkit: https://github.com/moby/buildkit

**Comment by chengshiwen** [comment]
@wonderflow @hongchaodeng

**Conclusion: we cannot use `buildkit` as library**

Now we use `docker build -t image` and `docker push image` commands in code, which need `docker cli client` and `docker daemon server` (using a VM to build docker images on a MAC or windows).

As for `buildkit`, it is composed of the `buildkitd` daemon and the `buildctl` client. While the `buildctl` client is available for `Linux`, `macOS`, and `Windows`, the `buildkitd` daemon is only available for Linux currently. In other words, even if we introduce `buildkit` to remove the `docker` command, we cannot compile the cross-platform binary.

At the same time, I also did research and test on the following repos, and the problems still exists:

- [buildkit](https://github.com/moby/buildkit): https://github.com/moby/buildkit
  - [Daemonless](https://github.com/moby/buildkit#daemonless): To run the client and an ephemeral daemon only in a single container ("daemonless mode")
- [img](https://github.com/genuinetools/img): https://github.com/genuinetools/img
  - This works only for Linux. Compile and run in a container if you're on Windows or MacOS
- [buildah](https://github.com/containers/buildah): https://github.com/containers/buildah
  - Daemonless absolutely, but only for linux
- [kaniko](https://github.com/GoogleContainerTools/kaniko): https://github.com/GoogleContainerTools/kaniko
  - Building and pushing image by running kaniko only works in container, see [Running kaniko](https://github.com/GoogleContainerTools/kaniko#running-kaniko)

So, we have two choices to choose:

1. Nothing to be changed, since docker is more popular in developers
2. Replace local `docker` binary with `docker client` library, which also means that `docker daemon` is required

WDYT?

**Comment by zzxwill** [comment]
@chengshiwen Very elaborated research, nice!
>Now we use docker build -t image and docker push image commands in code

Specifically, do you mean `buildx`? AFAIK, docker could not build cross-platform images. And we use docker buildx
https://github.com/oam-dev/kubevela/blob/master/.github/workflows/registry.yml#L48

**Comment by chengshiwen** [comment]
@zzxwill `buildx` is a Docker CLI plugin for extended build capabilities with [BuildKit](https://github.com/moby/buildkit). And this issue we discuss is the [code lines](https://github.com/oam-dev/kubevela/blob/d8eb7d687c4e50f3e79bc726eeaf81ff08a3b899/pkg/builtin/build/build.go#L104):
```
// TODO(hongchaodeng): remove this dependency by using go lib
cmd := exec.Command("docker", "build", "-t", image, "-f", b.Docker.File, b.Docker.Context)
```

More details, please refer to `https://docs.docker.com/buildx/working-with-buildx/#build-with-buildx`

Buildx builds using the BuildKit engine and does not require DOCKER_BUILDKIT=1 environment variable to start the builds.

The docker buildx build command supports features available for docker build, including features such as outputs configuration, inline build caching, and specifying target platform. In addition, Buildx also supports new features that are not yet available for regular docker build like building manifest lists, distributed caching, and exporting build results to OCI image tarballs.

**Comment by wonderflow** [comment]
@chengshiwen Thanks! Very appreciate for this research! As a result, I think we don't need to change for now. And we should replace the TODO to refer to this issue, so the conclusion can be seen by others. After that, we may close this issue.

**Comment by chengshiwen** [comment]
Got it
